spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j_stock_notify
    username: root
    password: dusgml1108!

  jpa:
    # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    hibernate:
      ddl-auto: none
    # true 설정시 JPA 쿼리문 확인 가능
    show-sql: true
    # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    properties:
      hibernate:
        format_sql: true